//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Room.
    /// </summary>
    //  *** Start programmer edit section *** (Room CustomAttributes)

    //  *** End programmer edit section *** (Room CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RoomE", new string[] {
            "Number as \'Number\'",
            "Floor as \'Floor\'",
            "Description as \'Description\'"})]
    [View("RoomL", new string[] {
            "Number as \'Number\'",
            "Floor as \'Floor\'",
            "Description as \'Description\'"})]
    public class Room : ICSSoft.STORMNET.DataObject
    {
        
        private int fFloor;
        
        private int fNumber;
        
        private string fDescription;
        
        //  *** Start programmer edit section *** (Room CustomMembers)

        //  *** End programmer edit section *** (Room CustomMembers)

        
        /// <summary>
        /// Floor.
        /// </summary>
        //  *** Start programmer edit section *** (Room.Floor CustomAttributes)

        //  *** End programmer edit section *** (Room.Floor CustomAttributes)
        public virtual int Floor
        {
            get
            {
                //  *** Start programmer edit section *** (Room.Floor Get start)

                //  *** End programmer edit section *** (Room.Floor Get start)
                int result = this.fFloor;
                //  *** Start programmer edit section *** (Room.Floor Get end)

                //  *** End programmer edit section *** (Room.Floor Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Room.Floor Set start)

                //  *** End programmer edit section *** (Room.Floor Set start)
                this.fFloor = value;
                //  *** Start programmer edit section *** (Room.Floor Set end)

                //  *** End programmer edit section *** (Room.Floor Set end)
            }
        }
        
        /// <summary>
        /// Number.
        /// </summary>
        //  *** Start programmer edit section *** (Room.Number CustomAttributes)

        //  *** End programmer edit section *** (Room.Number CustomAttributes)
        public virtual int Number
        {
            get
            {
                //  *** Start programmer edit section *** (Room.Number Get start)

                //  *** End programmer edit section *** (Room.Number Get start)
                int result = this.fNumber;
                //  *** Start programmer edit section *** (Room.Number Get end)

                //  *** End programmer edit section *** (Room.Number Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Room.Number Set start)

                //  *** End programmer edit section *** (Room.Number Set start)
                this.fNumber = value;
                //  *** Start programmer edit section *** (Room.Number Set end)

                //  *** End programmer edit section *** (Room.Number Set end)
            }
        }
        
        /// <summary>
        /// Description.
        /// </summary>
        //  *** Start programmer edit section *** (Room.Description CustomAttributes)

        //  *** End programmer edit section *** (Room.Description CustomAttributes)
        [StrLen(255)]
        public virtual string Description
        {
            get
            {
                //  *** Start programmer edit section *** (Room.Description Get start)

                //  *** End programmer edit section *** (Room.Description Get start)
                string result = this.fDescription;
                //  *** Start programmer edit section *** (Room.Description Get end)

                //  *** End programmer edit section *** (Room.Description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Room.Description Set start)

                //  *** End programmer edit section *** (Room.Description Set start)
                this.fDescription = value;
                //  *** Start programmer edit section *** (Room.Description Set end)

                //  *** End programmer edit section *** (Room.Description Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RoomE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RoomE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RoomE", typeof(IIS.Hotel.Room));
                }
            }
            
            /// <summary>
            /// "RoomL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RoomL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RoomL", typeof(IIS.Hotel.Room));
                }
            }
        }
    }
}
